# Copyright 2020 Traceable, Inc.
#
# Licensed under the Apache License, Version 2.0 (the “License”);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an “AS IS” BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


version: '3.7'
services: 

  crapi-identity:
    container_name: crapi-identity
    image: crapi-identity
    #ports:
    #  - "127.0.0.1:8080:8080"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - BLOCK_SHELL_INJECTION=false
      - JWT_SECRET=${JWT_SECRET}
      - MAILHOG_HOST=${MAILHOG_HOST}
      - MAILHOG_PORT=${MAILHOG_PORT}
      - MAILHOG_DOMAIN=${MAILHOG_DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_AUTH=${SMTP_AUTH}
      - SMTP_STARTTLS=${SMTP_STARTTLS}
      - WAIT_HOSTS=${WAIT_HOSTS}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL}
    depends_on:
      - postgresdb
      - mongodb
    healthcheck:
        test: curl 0.0.0.0:8080/identity/health_check
        interval: 15s
        timeout: 15s
        retries: 15
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 256M

  crapi-community:
    container_name: crapi-community
    image: crapi-community
    #ports:
    #  - "127.0.0.1:8087:8087"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - WAIT_HOSTS=${WAIT_HOSTS}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS}
    depends_on:
      - postgresdb
      - mongodb
      - crapi-identity
    healthcheck:
        test: curl 0.0.0.0:8087/community/home
        interval: 15s
        timeout: 15s
        retries: 15
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M

  crapi-workshop:
    container_name: crapi-workshop
    image: crapi-workshop
    #ports:
    #  - "127.0.0.1:8000:8000"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - WAIT_HOSTS=${WAIT_HOSTS}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS}
    depends_on:
      - postgresdb
      - mongodb
      - crapi-identity
      - crapi-community
    healthcheck:
        test: curl 0.0.0.0:8000/workshop/health_check/
        interval: 15s
        timeout: 15s
        retries: 15
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M

  crapi-web:
    container_name: crapi-web
    image: crapi-web
    ports:
      - "127.0.0.1:8888:80"
    environment:
      - GO_SERVICE=${GO_SERVICE}
      - JAVA_SERVICE=${JAVA_SERVICE}
      - PYTHON_SERVICE=${PYTHON_SERVICE}
      - WAIT_HOSTS=${WAIT_HOSTS}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL}
    depends_on:
      - crapi-community
      - crapi-identity
      - crapi-workshop
    healthcheck:
        test: curl 0.0.0.0:80/web/health
        interval: 15s
        timeout: 15s
        retries: 15
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M

  postgresdb:
    container_name: postgresdb
    image: 'postgres'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    #ports:
    #  - "127.0.0.1:5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M
  
  mongodb:
    container_name: mongodb
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #ports:
    #  - "127.0.0.1:27017:27017"
    volumes:
      - mongodb-data:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M

  mailhog:
    user: mailhog
    container_name: mailhog
    image: mailhog/mailhog
    environment:
      MH_MONGO_URI: ${MH_MONGO_URI}
      MH_STORAGE: mongodb
    ports: 
    #  - "127.0.0.1:1025:1025" # smtp server
      - "127.0.0.1:8025:8025" # Mail ui
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M

volumes:
  mongodb-data:
  postgresql-data:
